spring.application.name=auto-ecole-senegal

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/autoecole
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=elhadjimodoufaye
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialisation des données de départ
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Désactiver open-in-view (bonne pratique)
spring.jpa.open-in-view=false

# Serveur
server.port=8080

# Upload fichiers (images / vidéos)
upload.dir=uploads
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Dates JSON en ISO-8601 (pas de tableau [2024,1,15,...])
spring.jackson.serialization.write-dates-as-timestamps=false

# JWT
jwt.secret=4e616f4b65795365637265744175746545636f6c6553656e6567616c323032346b6579546f6b656e53656372657441757468
jwt.expiration=86400000
